[package]
name = "pyo3-pylogger"
version = "0.3.0"
edition = "2021"
authors = ["Dylan Bobby Storey <dylan.storey@gmail.com>"]
description = "Enables `log` for pyo3 based Rust applications using the `logging` modules."
publish = ["crates-io"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/dylanbstorey/pyo3-pylogger"
repository = "https://github.com/dylanbstorey/pyo3-pylogger"
documentation = "https://github.com/dylanbstorey/pyo3-pylogger"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = { version = ">=0.21" }
log = { version = "0.4" }
phf = { version = "0.11", features = ["macros"] , optional = true }

[features]
default = []
kv = ["log/kv", "phf"]
